# Generated by Django 4.2.2 on 2023-06-25 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('users', '0002_administrator_company_delete_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='order',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_administrator', to='users.administrator'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_company', to='users.company'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='bill',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_administrator', to='users.administrator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_company', to='users.company'),
        ),
    ]
